### ISSUE TITLE
[Chore] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by bang-wol** [security-vigilante/geekhub#1]
## ✨ 작업 내용
프로젝트 초기 세팅

## ✅ TODO
- [x] Issue 템플릿 생성
- [x] Pull Request 템플릿 생성
- [x] Next.js 프로젝트 생성
- [x] ESLint 설정
- [x] Prettier 설정
- [x] 컬러 정의
- [x] 폴더 구조 정리
- [x] husky 설정
- [x] 필요한 라이브러리, 패키지 설치
- [x] Github Action 추가
