### ISSUE TITLE
[Feat] Floating 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by printjin-gmailcom** [security-vigilante/geekhub#12]
## ✨ 작업 내용
공통으로 사용되는 Floating 컴포넌트 퍼블리싱

## 🖼️ 스크린샷 (선택)
![캡처](https://github.com/user-attachments/assets/31859985-1f0e-4b87-8f0e-5509c3ff5f47)

## ✅ TODO
- [ ] Floating - top, hovered
- [ ] Floating - top, Enabled
- [ ] Floating - ask, hovered
- [ ] Floating - ask, Enabled
