### ISSUE TITLE
[Feat] 취약점 DB 페이지 기능 구현

### ISSUE THREAD

**Issue by sockki** [security-vigilante/geekhub#46]
## ✨ 작업 내용
취약점 DB 페이지 기능 구현 이슈입니다.
주로 크롤링 관련 기능 구현이 예상됩니다.

## ✅ TODO
- [ ]  비 로그인 시 블러 처리

크롤링 데이터 가져오기
- [x] 전체 데이터 가져오기
- [x] 번역 하기
- [x] firebase에 저장하기
- [x] 회사 이름 추출하기
- [ ] 최신 크롤링 데이터 매일 가져오는 함수 짜기
- [x] 페이지네이션 구현하기

검색 기능
- [x]  검색한 데이터가 정상적으로 나오는지
- [x]  검색 결과가 없을 경우의 예외처리가 되있는지
- [x]  검색어의 정규식 처리가 제대로 되있는지 ( 띄어쓰기 및 특수문자 )
- [x]  미입력 등 특수한 케이스의 예외처리가 되있는지

라벨
- [x] 최신 아티클 10개에 new 붙이기
- [x] 조회수 상단 10개 hot 붙이기
- [x] 최신순, 조회수 순 정렬 구현하기

배너 카드
- [x] 최신순, 조회수 순 마다 상단 3개의 배너 카드에 연결하기

스크랩 및 공유
- [x] 스크랩 기능 구현
- [x] 공유 기능 구현

상세 페이지
- [x]  클릭한 게시글의 내용이 잘 표기되는지
    - [x]  HOT, NEW 태그가 기획대로 잘 붙어있는지
    - [x]  제목 및 시간, 내용이 정상적으로 불러오는지
- [x]  핀 기능 및 공유 기능이 정상적으로 동작하는지
- [x]  비슷한 정보글이 로직(키워드 및 제품군, 최신글 기준)에 맞게 불러와지는지
- [x]  비슷한 정보글의 태그 및 공유기능이 동작하는지
- [x]  쳇봇 플로팅 아이콘이 정상적으로 떠있는지
