### ISSUE TITLE
[Chore] Vercel 배포

### ISSUE THREAD

**Issue by bang-wol** [security-vigilante/geekhub#47]
## ✨ 작업 내용
Vercel과 Github Actions 이용하여 배포 진행

## 🖼️ 스크린샷 (선택)
<img width="1248" alt="스크린샷 2024-08-26 오전 11 20 45" src="https://github.com/user-attachments/assets/b2c6b1c8-9c82-4141-9657-374318e7f3ae">

## ✅ TODO
- [x] vercel에 프로젝트 import
- [x] 시크릿 변수 추가
- [ ] build 파일 추가
- [ ] workflows 추가
