### ISSUE TITLE
[Feat] 레포지토리 검사 페이지 기능 고도화

### ISSUE THREAD

**Issue by chaduhwan** [security-vigilante/geekhub#68]
## ✨ 작업 내용
중간 발표 이후 멘토님 피드백 및 QA 이후 수정될 사항들 입니다.
## ✅ TODO
- [x]  인포박스 코드블록이랑 위에 헤더 색깔 구분시키기 ⇒ 까만색
- [x]  인포박스 코드블록 패딩 위 1.2 밑 1.6

- [ ]  레포리스트 페이지에서 검사페이지로 이동이 느린것 ⇒ 빠르게 prefetch or 로딩 페이지 넣기
- [x]  로그아웃 ⇒ db를 따로 관리가 아니라 유저안으로
- [x]  파일, 폴더 아이템 커서 포인터
- [x]  파일, 폴더 아이템 엘리스 처리
- [x]  파일, 폴더 아이템 체크박스
- [x]  사이드바 보더 겹침 수정
- [x]  사이드바 헤더, 브레드 크럼블, 뒤로가기 는 픽스하기
- [x]  사이드바 height 유연하게 가져가기
- [ ]  북마크 빼기

- [x]  코드 포멧 가로길이 수정
- [x]  코드 포멧 글씨 크기 18px로 수정
- [x]  밑에 단일 검사하기 삭제 ⇒ 폴더 전체검사를 하나의 파일을 검사하기 ? 처럼 갯수에 상관없이 아예 모달 띄우기
- [x]  다중 선택 누르면 체크박스 모두 체크되게 하기
- [x]  다중 검사 시작시 첫번째 파일을 코드 포멧에 나오게 하기
- [x]  뒤로갓다가 사이드에 현재 레포꺼를 불러오는게 안되는거 ⇒ 레이아웃 말고 템플릿
- [x]  프로그레스바 빼기
- [ ]  취약점 아코디언 하기
- [x]  수정할코드 크기 줄이기 2.4rem
- [x]  취약코드 배경색 인포박스랑 맞추기
