### ISSUE TITLE
[Feat] 저장소 페이지 예외 처리 및 디자인 수정

### ISSUE THREAD

**Issue by bang-wol** [security-vigilante/geekhub#69]
## ✨ 작업 내용
- 저장소 페이지 예외 처리 및 디자인 디테일 수정 작업 진행할 예정입니다. 

## ✅ TODO
- [x] empty 케이스 추가
- [x] input 예외 처리
- [ ] 박스 크기 일정하게
- [x] 버튼 영역 수정
- [x] 카드 컴포넌트 디자인 수정
- [x] 레포 검사 타입 연동
- [x] 레포 검사 결과 users 아래 컬렉션에 저장
