### ISSUE TITLE
[Feat] 폰트 및 헤더 수정

### ISSUE THREAD

**Issue by printjin-gmailcom** [security-vigilante/geekhub#70]
## ✨ 작업 내용
폰트 변경 및 헤더 수정 예정입니

## ✅ TODO
- [x] 폰트 변경
- [x] 헤더 우측 정렬
- [x] 헤더 호버 시 색상 변경
- [x] 헤더 로그아웃 버튼 추가
