### ISSUE TITLE
[Refactor] 오류 수정 및 개선

### ISSUE THREAD

**Issue by bang-wol** [security-vigilante/geekhub#77]
## ✨ 작업 내용
오류 수정 및 개선

## ✅ TODO
- [x] 로그인 페이지 디자인 개선
- [x] 문의하기 info 줄 간격 통일하기
- [x] 문의하기 모달 닫기
- [x] 배포 사이트 로그인 확인
- [x] 배포 사이트 취약점 DB 접속 안 되는 오류 해결
- [x] 헤더 로그아웃 버튼 이벤트 수정
- [x] 로그아웃 시 코드 검사 결과 삭제
- [x] type, sort 버튼 크기 맞추기
- [x] 실시간 토픽 db 삭제하고 테스트용으로 수정
- [ ] 콘솔 에러 해결
- [ ] 뒤로가기 버튼 누르면 검사 상태 바로 변경
- [x] github actions 글씨 스타일 통일
- [ ] 페이지네이션 시작, 마지막 페이지 화살표 없애기
