### ISSUE TITLE
[Feat] Infobox 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by printjin-gmailcom** [security-vigilante/geekhub#8]
## ✨ 작업 내용
공통으로 사용되는 Infobox 컴포넌트 퍼블리싱

## 🖼️ 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/f017db5f-4ebd-4fb9-9f72-e312a838abcb)

## ✅ TODO
- [x] Info Box Red
- [x] Info Box Primary
- [x] Info Box Gray
