### ISSUE TITLE
[Refactor] 오류 해결, 성능 개선

### ISSUE THREAD

**Issue by bang-wol** [security-vigilante/geekhub#81]
## ✨ 작업 내용
해결하지 못한 자잘한 오류 해결하고 불필요한 업데이트 방지하여 최적화하고 성능 개선

## ✅ TODO
- [x] console 오류 해결
- [x] 페이지네이션 화살표 예외 처리
- [ ] 불필요한 업데이트 방지하여 성능 최적화
- [ ] 로그아웃시 스크랩도 삭제
