### ISSUE TITLE
[Feat] Switch 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by chaduhwan** [security-vigilante/geekhub#9]
## ✨ 작업 내용
공통 컴포넌트 switch 작업 내용입니다.
4가지 switch를 구현할 예정입니다.
radix ui 라이브러리를 사용할 예정입니다.
## 🖼️ 스크린샷 (선택)
<img width="447" alt="image" src="https://github.com/user-attachments/assets/28df2ddb-ca20-45cb-b314-53be7c3fbda0">

## ✅ TODO
- [x] selected = true , Icon = true
- [x] selected = true , Icon = false
- [x] selected = false , Icon = true
- [x] selected = false , Icon = false
